version: '3.8'

services:
  backend:
    build:
      context: ./backend
      target: prod
    ports:
      - "5000:5000"
    networks:
      - app-network
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./frontend
      target: prod
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - NODE_ENV=production

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cafe
      - TZ=Europe/Istanbul
      - default-time-zone='+03:00'
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysql", "-u", "root", "-proot", "-e", "SELECT 1"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 20s

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
